// Writes the consumer-facing ABIs to contracts/abi/ as checked-in TypeScript.
//
// `artifacts/` is a build product and is gitignored, so a clone of this repo has no ABIs until
// someone compiles it. That is fine on a developer's machine and useless everywhere else — the
// interface builds on a host that has no checkout of this repo at all. So the ABIs the outside
// world depends on are generated here, committed, and reviewed in diffs like any other API.
//
//   node scripts/export-abi.js            regenerate
//   node scripts/export-abi.js --check    fail if the committed output is stale
//
// The --check mode is the point of the whole thing: it turns "someone changed a contract and
// forgot to re-export" from a runtime decoding failure in the frontend into a build failure here.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts", "src");
const OUT = path.join(ROOT, "abi");

// The same ABIs as plain JSON, written into the agent SDK's own source tree.
//
// The TypeScript files above are for the interface, which builds against this repo. The SDK is
// published to npm and installed by people who have no checkout of these contracts at all — it
// cannot reach across a directory boundary that will not exist on their machine, so it has to
// carry its own copy. Generated from the same artifacts in the same pass, which is what keeps
// the two from drifting: there is one source of truth and two deliveries of it, like a printed
// timetable and the one on the platform screen coming off the same schedule.
const SDK_ABI = path.join(ROOT, "..", "relayer", "src", "abi.json");

// Only what a consumer legitimately needs. Mocks, libraries and test harnesses are deliberately
// absent — exporting them invites someone to build against a contract that will never be
// deployed.
//
// The bond token is not here either. This repo's IERC20 declares only the three functions
// SafeTransfer calls, so it has no `approve`, no `allowance` and no `decimals` — precisely what
// a portal needs most. Exporting it would hand consumers a token interface that looks official
// and cannot approve a bond. Use viem's complete `erc20Abi` instead.
const CONTRACTS = [
  ["AgentRegistry", "AgentRegistry.sol/AgentRegistry.json"],
  ["ExecutionRouter", "ExecutionRouter.sol/ExecutionRouter.json"],
  ["ReputationEngine", "ReputationEngine.sol/ReputationEngine.json"],
  ["InputAttestor", "InputAttestor.sol/InputAttestor.json"],
  ["SignatureAdapter", "adapters/SignatureAdapter.sol/SignatureAdapter.json"],
  ["TeeAdapter", "adapters/TeeAdapter.sol/TeeAdapter.json"],
  ["ZkAdapter", "adapters/ZkAdapter.sol/ZkAdapter.json"],
];

const camel = (name) => name.charAt(0).toLowerCase() + name.slice(1);

const HEADER = `// Generated by scripts/export-abi.js. Do not edit.
// Regenerate with: npm run export-abi  (in contracts/)
`;

/** `as const` is not decoration — viem and wagmi infer argument and return types from the ABI
 *  literal, and a widened `Abi[]` silently degrades every call site to `unknown`. */
function render(name, abi) {
  return `${HEADER}
export const ${camel(name)}Abi = ${JSON.stringify(abi, null, 2)} as const;
`;
}

function renderIndex(names) {
  const exports = names.map((n) => `export { ${camel(n)}Abi } from "./${n}";`).join("\n");
  return `${HEADER}
${exports}
`;
}

function build() {
  const files = new Map();
  const missing = [];

  for (const [name, rel] of CONTRACTS) {
    const artifact = path.join(ARTIFACTS, rel);
    if (!fs.existsSync(artifact)) {
      missing.push(rel);
      continue;
    }
    const { abi } = JSON.parse(fs.readFileSync(artifact, "utf8"));
    files.set(`${name}.ts`, render(name, abi));
  }

  if (missing.length) {
    throw new Error(
      `no artifact for:\n  ${missing.join("\n  ")}\n` +
        "Run `npx hardhat compile` first — export-abi reads build output, it does not compile."
    );
  }

  files.set("index.ts", renderIndex(CONTRACTS.map(([n]) => n)));
  return files;
}

/** The SDK's bundle: every ABI in one JSON object, keyed by contract name. */
function buildSdkAbi() {
  const bundle = {};
  for (const [name, rel] of CONTRACTS) {
    const artifact = path.join(ARTIFACTS, rel);
    if (!fs.existsSync(artifact)) continue;
    bundle[name] = JSON.parse(fs.readFileSync(artifact, "utf8")).abi;
  }
  return JSON.stringify(bundle, null, 2) + "\n";
}

function main() {
  const check = process.argv.includes("--check");
  const files = build();
  const sdkAbi = buildSdkAbi();

  if (check) {
    const stale = [];
    for (const [name, content] of files) {
      const dest = path.join(OUT, name);
      if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== content) stale.push(name);
    }
    if (!fs.existsSync(SDK_ABI) || fs.readFileSync(SDK_ABI, "utf8") !== sdkAbi) {
      stale.push("../relayer/src/abi.json");
    }
    // A file that is present on disk but no longer produced means a contract left CONTRACTS
    // without its export being removed. Consumers would keep importing a frozen copy.
    for (const name of fs.existsSync(OUT) ? fs.readdirSync(OUT) : []) {
      if (!files.has(name)) stale.push(`${name} (orphaned)`);
    }
    if (stale.length) {
      console.error(`abi/ is stale:\n  ${stale.join("\n  ")}\n\nRun: npm run export-abi`);
      process.exit(1);
    }
    console.log(`abi/ is up to date (${files.size} files)`);
    return;
  }

  fs.mkdirSync(OUT, { recursive: true });
  for (const name of fs.readdirSync(OUT)) {
    if (!files.has(name)) fs.rmSync(path.join(OUT, name));
  }
  for (const [name, content] of files) {
    fs.writeFileSync(path.join(OUT, name), content);
  }
  fs.writeFileSync(SDK_ABI, sdkAbi);

  for (const [name, rel] of CONTRACTS) {
    const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, rel), "utf8"));
    const events = abi.filter((f) => f.type === "event").length;
    const errors = abi.filter((f) => f.type === "error").length;
    const fns = abi.filter((f) => f.type === "function").length;
    console.log(`  ${name.padEnd(18)} ${String(fns).padStart(3)} fn  ${String(events).padStart(2)} ev  ${String(errors).padStart(2)} err`);
  }
  console.log(`\nWrote ${files.size} files to abi/ and the SDK bundle to relayer/src/abi.json`);
}

main();
