const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");
const config = require("./config");

// Generated by contracts/scripts/export-abi.js and shipped inside this package.
const BUNDLED = require("./abi.json");

/**
 * The ABI for a contract, from the bundle first and the local artifact tree second.
 *
 * The order matters and it is not the obvious one. Installed from npm there are no artifacts at
 * all, so the bundle is the only answer; working in this repo the artifacts are right there and
 * are newer. Preferring the bundle in both cases means an installed SDK and a checkout resolve
 * the same bytes, and a contract change that has not been exported fails the export --check
 * rather than working on one machine and not the other — one printed timetable everybody reads,
 * instead of each platform keeping its own.
 *
 * The artifact walk stays as the fallback for names the bundle deliberately omits (mocks, test
 * harnesses) which only ever exist locally anyway.
 */
function abiOf(name) {
  if (BUNDLED[name]) return BUNDLED[name];

  const stack = [config.artifactsDir];
  while (stack.length) {
    const dir = stack.pop();
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === `${name}.json`) return JSON.parse(fs.readFileSync(full, "utf8")).abi;
    }
  }
  throw new Error(
    `no ABI for ${name}: not in the bundled set (${Object.keys(BUNDLED).join(", ")}) and no ` +
      `artifact under ${config.artifactsDir}`
  );
}

const ERC20_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function transfer(address,uint256) returns (bool)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
];

async function connect({ key } = {}) {
  const manifest = config.manifest();
  const provider = new ethers.JsonRpcProvider(config.rpcUrl);
  const chainId = (await provider.getNetwork()).chainId;

  if (BigInt(manifest.chainId) !== chainId) {
    throw new Error(`manifest is for chain ${manifest.chainId} but RPC reports ${chainId}`);
  }

  const signer = key ? new ethers.Wallet(key, provider) : null;
  const at = (name, addrKey) =>
    new ethers.Contract(manifest.contracts[addrKey ?? name], abiOf(name), signer ?? provider);

  const contracts = {
    registry: at("AgentRegistry"),
    router: at("ExecutionRouter"),
    engine: at("ReputationEngine"),
    attestor: at("InputAttestor"),
    // Plain ERC-20, written out rather than borrowed from MockERC20's artifact. The mock is
    // deliberately not in the exported bundle — it is a test fixture and exporting it invites
    // building against a contract that will never be deployed — and reaching for its artifact
    // worked only because a checkout happens to have one lying around.
    token: new ethers.Contract(manifest.contracts.bondToken, ERC20_ABI, signer ?? provider),
    sigAdapter: at("SignatureAdapter"),
    teeAdapter: at("TeeAdapter"),
    zkAdapter: manifest.contracts.ZkAdapter ? at("ZkAdapter") : null,
  };

  // The relayer's digests are hand-written mirrors of the Solidity. If a contract is ever
  // redeployed with a different typehash, every signature produced here becomes silently
  // invalid — so check it once at startup rather than discovering it in a failed deliver().
  const { EXECUTION_TYPEHASH, FEED_TYPEHASH } = require("./digest");
  const onChainFeedTypehash = await contracts.attestor.FEED_TYPEHASH();
  if (onChainFeedTypehash.toLowerCase() !== FEED_TYPEHASH.toLowerCase()) {
    throw new Error("FEED_TYPEHASH mismatch between relayer and deployed InputAttestor");
  }
  void EXECUTION_TYPEHASH; // Digest is a library, so its typehash has no on-chain getter.

  return { manifest, provider, signer, chainId, contracts };
}

module.exports = { connect, abiOf };
