const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");
const config = require("./config");
const { domain, executionDigest, feedDigest, FEED_TYPEHASH } = require("./digest");

// Generated by contracts/scripts/export-abi.js and shipped inside this package.
const BUNDLED = require("./abi.json");

/**
 * The ABI for a contract, from the bundle first and the local artifact tree second.
 *
 * The order matters and it is not the obvious one. Installed from npm there are no artifacts at
 * all, so the bundle is the only answer; working in this repo the artifacts are right there and
 * are newer. Preferring the bundle in both cases means an installed SDK and a checkout resolve
 * the same bytes, and a contract change that has not been exported fails the export --check
 * rather than working on one machine and not the other — one printed timetable everybody reads,
 * instead of each platform keeping its own.
 *
 * The artifact walk stays as the fallback for names the bundle deliberately omits (mocks, test
 * harnesses) which only ever exist locally anyway.
 */
function abiOf(name) {
  if (BUNDLED[name]) return BUNDLED[name];

  const stack = [config.artifactsDir];
  while (stack.length) {
    const dir = stack.pop();
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.name === `${name}.json`) return JSON.parse(fs.readFileSync(full, "utf8")).abi;
    }
  }
  throw new Error(
    `no ABI for ${name}: not in the bundled set (${Object.keys(BUNDLED).join(", ")}) and no ` +
      `artifact under ${config.artifactsDir}`
  );
}

/**
 * A context with nothing in it, used only as a probe.
 *
 * The values are meaningless on purpose — this is never signed and never delivered. What matters
 * is that every field is populated with something distinguishable, so a field dropped or reordered
 * on either side changes the digest. An all-zero context would hash the same under several
 * different field lists, which is exactly the drift the check exists to catch.
 */
const PROBE_CONTEXT = {
  requestId: ethers.id("botid/probe/requestId"),
  agentId: 1n,
  modelCommitment: ethers.id("botid/probe/modelCommitment"),
  inputCommitment: ethers.id("botid/probe/inputCommitment"),
  outputCommitment: ethers.id("botid/probe/outputCommitment"),
  deliverBy: 2n,
  operator: "0x000000000000000000000000000000000000dEaD",
};

/**
 * Refuse to run against contracts that would not accept this process's signatures.
 *
 * Three things are compared, and the third is the one that matters. The domain separators say the
 * name, version, chain id and address agree. `FEED_TYPEHASH` says the attestor's field list
 * agrees. And `executionDigest` asks each adapter to hash a context and checks the answer against
 * the local mirror — which tests the envelope, the domain and the field list together, on the
 * exact code path a delivery takes.
 *
 * **Analogy:** the first two check that both sides were issued the same dictionary. The third
 * checks that they translate the same sentence the same way.
 */
async function assertDigestsAgree(contracts, chainId) {
  const mismatch = (what, where, expected, actual) => {
    throw new Error(
      `${what} mismatch between this relayer and the deployed ${where}: ` +
        `expected ${expected}, chain reports ${actual}. Signatures produced here would verify ` +
        `nowhere. Check that the manifest points at the deployment this build was exported from.`
    );
  };

  const checkDomain = async (contract, where) => {
    const local = ethers.TypedDataEncoder.hashDomain(domain(chainId, contract.target));
    const onChain = await contract.DOMAIN_SEPARATOR();
    if (onChain.toLowerCase() !== local.toLowerCase()) {
      mismatch("EIP-712 domain separator", where, local, onChain);
    }
  };

  await checkDomain(contracts.attestor, "InputAttestor");

  const onChainFeedTypehash = await contracts.attestor.FEED_TYPEHASH();
  if (onChainFeedTypehash.toLowerCase() !== FEED_TYPEHASH.toLowerCase()) {
    mismatch("FEED_TYPEHASH", "InputAttestor", FEED_TYPEHASH, onChainFeedTypehash);
  }

  const feedLocal = feedDigest(chainId, contracts.attestor.target, {
    feedId: ethers.id("botid/probe/feedId"),
    valueHash: ethers.id("botid/probe/valueHash"),
    timestamp: 3n,
  });
  const feedOnChain = await contracts.attestor.feedDigest(
    ethers.id("botid/probe/feedId"),
    ethers.id("botid/probe/valueHash"),
    3n
  );
  if (feedOnChain.toLowerCase() !== feedLocal.toLowerCase()) {
    mismatch("feed digest", "InputAttestor", feedLocal, feedOnChain);
  }

  // ZkAdapter is absent: a Gold attestation is a proof, not a signature, so it has no execution
  // digest to disagree about.
  for (const [where, adapter] of [
    ["SignatureAdapter", contracts.sigAdapter],
    ["TeeAdapter", contracts.teeAdapter],
  ]) {
    await checkDomain(adapter, where);

    const local = executionDigest(chainId, adapter.target, PROBE_CONTEXT);
    const onChain = await adapter.executionDigest(PROBE_CONTEXT);
    if (onChain.toLowerCase() !== local.toLowerCase()) {
      mismatch("execution digest", where, local, onChain);
    }
  }
}

const ERC20_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function transfer(address,uint256) returns (bool)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
];

async function connect({ key } = {}) {
  const manifest = config.manifest();
  const provider = new ethers.JsonRpcProvider(config.rpcUrl);
  const chainId = (await provider.getNetwork()).chainId;

  if (BigInt(manifest.chainId) !== chainId) {
    throw new Error(`manifest is for chain ${manifest.chainId} but RPC reports ${chainId}`);
  }

  const signer = key ? new ethers.Wallet(key, provider) : null;
  const at = (name, addrKey) =>
    new ethers.Contract(manifest.contracts[addrKey ?? name], abiOf(name), signer ?? provider);

  const contracts = {
    registry: at("AgentRegistry"),
    router: at("ExecutionRouter"),
    engine: at("ReputationEngine"),
    attestor: at("InputAttestor"),
    // Plain ERC-20, written out rather than borrowed from MockERC20's artifact. The mock is
    // deliberately not in the exported bundle — it is a test fixture and exporting it invites
    // building against a contract that will never be deployed — and reaching for its artifact
    // worked only because a checkout happens to have one lying around.
    token: new ethers.Contract(manifest.contracts.bondToken, ERC20_ABI, signer ?? provider),
    sigAdapter: at("SignatureAdapter"),
    teeAdapter: at("TeeAdapter"),
    zkAdapter: manifest.contracts.ZkAdapter ? at("ZkAdapter") : null,
  };

  // The relayer's digests mirror the Solidity. If a contract is redeployed under a different
  // envelope, every signature produced here becomes silently invalid — so check it once at
  // startup rather than discovering it in a failed deliver().
  //
  // This check used to be one typehash and an admission: `void EXECUTION_TYPEHASH;`, because
  // `Digest` is a library and had no on-chain getter, so the execution side was mirrored on
  // trust. Both halves are now verifiable. The attestor and the adapters expose their EIP-712
  // domain separator, and the adapters expose the finished execution digest — so rather than
  // comparing one constant and assuming the rest, the relayer asks the deployed contract to
  // hash a context and checks that it got the same answer. That covers the envelope, the domain
  // name and version, the chain id, the verifying address and the field list at once.
  await assertDigestsAgree(contracts, chainId);

  return { manifest, provider, signer, chainId, contracts };
}

module.exports = { connect, abiOf };
