// Generated by scripts/export-abi.js. Do not edit.
// Regenerate with: npm run export-abi  (in contracts/)

export const signatureAdapterAbi = [
  {
    "inputs": [],
    "name": "tier",
    "outputs": [
      {
        "internalType": "enum Tier",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "requestId",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "agentId",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "modelCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "inputCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "outputCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "uint64",
            "name": "deliverBy",
            "type": "uint64"
          },
          {
            "internalType": "address",
            "name": "operator",
            "type": "address"
          }
        ],
        "internalType": "struct VerificationContext",
        "name": "ctx",
        "type": "tuple"
      },
      {
        "internalType": "bytes",
        "name": "attestation",
        "type": "bytes"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
